// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CodeDocument struct {
	Reference  string         `json:"reference"`
	Language   *string        `json:"language,omitempty"`
	Segments   []*CodeSegment `json:"segments"`
	NonText    bool           `json:"nonText"`
	Error      *string        `json:"error,omitempty"`
	Warning    *string        `json:"warning,omitempty"`
	FocusID    *string        `json:"focusId,omitempty"`
	Files      []*FsEntry     `json:"files"`
	Symbols    []*FsEntry     `json:"symbols"`
	ParentHref *string        `json:"parentHref,omitempty"`
}

type CodeSegment struct {
	Text      string  `json:"text"`
	Href      *string `json:"href,omitempty"`
	AnchorID  *string `json:"anchorId,omitempty"`
	IsLink    bool    `json:"isLink"`
	IsDef     bool    `json:"isDef"`
	Reference *string `json:"reference,omitempty"`
}

type Doc struct {
	Name      string  `json:"name"`
	Signature *string `json:"signature,omitempty"`
	DocString *string `json:"docString,omitempty"`
}

type FsEntry struct {
	Name      string `json:"name"`
	Reference string `json:"reference"`
	IsDir     bool   `json:"isDir"`
}

type GraphEdge struct {
	From string   `json:"from"`
	To   string   `json:"to"`
	Kind EdgeKind `json:"kind"`
}

// Graph fact node (atom, file, or module). id is the canonical reference string.
type GraphNode struct {
	ID       string   `json:"id"`
	Kind     NodeKind `json:"kind"`
	Label    string   `json:"label"`
	ParentID *string  `json:"parentId,omitempty"`
}

// Focus-driven lazy neighborhood. May be incomplete (Seed-style).
type Neighborhood struct {
	Focus      *GraphNode   `json:"focus"`
	Nodes      []*GraphNode `json:"nodes"`
	Edges      []*GraphEdge `json:"edges"`
	Incomplete bool         `json:"incomplete"`
}

type Query struct {
}

type EdgeKind string

const (
	EdgeKindUses    EdgeKind = "USES"
	EdgeKindUsedBy  EdgeKind = "USED_BY"
	EdgeKindImports EdgeKind = "IMPORTS"
)

var AllEdgeKind = []EdgeKind{
	EdgeKindUses,
	EdgeKindUsedBy,
	EdgeKindImports,
}

func (e EdgeKind) IsValid() bool {
	switch e {
	case EdgeKindUses, EdgeKindUsedBy, EdgeKindImports:
		return true
	}
	return false
}

func (e EdgeKind) String() string {
	return string(e)
}

func (e *EdgeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EdgeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EdgeKind", str)
	}
	return nil
}

func (e EdgeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EdgeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EdgeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeKind string

const (
	NodeKindAtom   NodeKind = "ATOM"
	NodeKindFile   NodeKind = "FILE"
	NodeKindModule NodeKind = "MODULE"
)

var AllNodeKind = []NodeKind{
	NodeKindAtom,
	NodeKindFile,
	NodeKindModule,
}

func (e NodeKind) IsValid() bool {
	switch e {
	case NodeKindAtom, NodeKindFile, NodeKindModule:
		return true
	}
	return false
}

func (e NodeKind) String() string {
	return string(e)
}

func (e *NodeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeKind", str)
	}
	return nil
}

func (e NodeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
