package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
)

// RootDir is the resolver for the rootDir field.
func (r *queryResolver) RootDir(ctx context.Context) (string, error) {
	if r.Store == nil {
		return "", fmt.Errorf("store not configured")
	}
	return r.Store.RootDir(), nil
}

// Filesystem is the resolver for the filesystem field.
func (r *queryResolver) Filesystem(ctx context.Context, ref *string) ([]*FsEntry, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	return r.Store.Filesystem(ref)
}

// Neighborhood is the resolver for the neighborhood field.
func (r *queryResolver) Neighborhood(ctx context.Context, ref string) (*Neighborhood, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	return r.Store.Neighborhood(ref)
}

// Code is the resolver for the code field.
func (r *queryResolver) Code(ctx context.Context, ref string) (*CodeDocument, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	return r.Store.Code(ref)
}

// Doc is the resolver for the doc field.
func (r *queryResolver) Doc(ctx context.Context, ref string) (*Doc, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	return r.Store.Doc(ref)
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (*GraphNode, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	return r.Store.Node(id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
